### ISSUE TITLE
Say command doesnt copy mentions and emotes values

### ISSUE THREAD

**Issue by Niewidzialny84** [seker212/Discord_bot#17]

**Comment by Niewidzialny84** [comment]
Also won't copy whole message

**Comment by seker212** [comment]
.say command currently requires quotation mark to copy whole message 
 - Using it as `.say #channel1 My message to @user1` generates message on `channel1` with text: `My`. 
 - Using it as `.say #channel1 "My message to @user1"` generates message on `channel1` with text: `My message to @user1`. This message includes correct user mentions, roles mentions, server channel mentions, discord emotes, server emotes.
