### ISSUE TITLE
Fix line 75 in stuff.py 

### ISSUE THREAD

**Issue by Niewidzialny84** [seker212/Discord_bot#36]
There is a needed change that gone missing due not know error.
Replace the
`ctx` to `ctx.message`
[here](https://github.com/seker212/Discord_bot/blob/4f3f885193133badc21d4b2fe0dda7a4ce5297e1/stuff.py#L75)

**Comment by szyjah** [comment]
#39 the change is here

**Comment by Niewidzialny84** [comment]
It actually is false and dont work but i have a fix
