### ISSUE TITLE
Add special character support for ytplayer

### ISSUE THREAD

**Issue by seker212** [seker212/Discord_bot#66]
Command `.play` with special characters like `.play ryż` throws `UnicodeEncodeError: 'ascii' codec can't encode character '\u017c' in position 28: ordinal not in range(128)`. This is due to passing the text to URL, which by default does not use special characters. Those need to be accepted as e.g. UTF-8 and converted to percent-encoding before passing to URL.

**Comment by seker212** [comment]
Issue is referring to v1.x implementation, but it requires verification if v2.x also has this issue

**Comment by Niewidzialny84** [comment]
This was resolved in 2.0 version. All special characters are handled in queries correctly.
